import Head from "next/head";
import { useRouter } from "next/router";
import { useTranslation } from "react-i18next";
import Languages from "./Languages";
import Menu from "./Menu";
import { faInstagram, faLinkedin, faFacebook } from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

import React from "react";

function Social() {
  return (
    <div className="flex mx-auto my-2">
      <FontAwesomeIcon className="cursor-pointer mx-4 w-8"  icon={faInstagram} />
      <FontAwesomeIcon className="cursor-pointer mx-4 w-8"  icon={faLinkedin} />
      <FontAwesomeIcon className="cursor-pointer mx-4 w-8"  icon={faFacebook} />
    </div>
  );
}

function Layout({ children }: any) {
  const { t } = useTranslation("common");
  const router = useRouter();

  return (
    <>
      <Head>
        <title>FrenchHouse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col p-10 bg-gray-50">
        {!router.asPath.includes("/projects/") && <Languages />}
        <Menu />
        {children}
        <Social />
      </main>
    </>
  );
}

export default Layout;
