import Head from "next/head";
import { useRouter } from "next/router";
import { useTranslation } from "react-i18next";
import Languages from "./Languages";
import Menu from "./Menu";

function Layout({ children }: any) {
  const { t } = useTranslation("common");
  const router = useRouter();

  return (
    <>
      <Head>
        <title>AimArchitecture</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col p-10 bg-gray-50">
        <Languages />
        <Menu />
        {children}
      </main>
      <p className="pt-5 text-center font-thin">{t("footer.allRights")}</p>
    </>
  );
}

export default Layout;
